// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Count() {
  return window['go']['controllers']['App']['Count']();
}

export function CreateUser(arg1) {
  return window['go']['controllers']['App']['CreateUser'](arg1);
}

export function DeleteUserById(arg1) {
  return window['go']['controllers']['App']['DeleteUserById'](arg1);
}

export function GetUserByEmail(arg1) {
  return window['go']['controllers']['App']['GetUserByEmail'](arg1);
}

export function GetUserById(arg1) {
  return window['go']['controllers']['App']['GetUserById'](arg1);
}

export function GetUsers() {
  return window['go']['controllers']['App']['GetUsers']();
}

export function LoginUser(arg1) {
  return window['go']['controllers']['App']['LoginUser'](arg1);
}

export function Migration() {
  return window['go']['controllers']['App']['Migration']();
}

export function RefreshToken(arg1) {
  return window['go']['controllers']['App']['RefreshToken'](arg1);
}

export function RegisterUser(arg1) {
  return window['go']['controllers']['App']['RegisterUser'](arg1);
}

export function TimerMultiple() {
  return window['go']['controllers']['App']['TimerMultiple']();
}

export function TimerOff() {
  return window['go']['controllers']['App']['TimerOff']();
}

export function UpdateUser(arg1) {
  return window['go']['controllers']['App']['UpdateUser'](arg1);
}
