// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Count():Promise<number>;

export function CreateUser(arg1:models.User):Promise<void>;

export function DeleteUserById(arg1:string):Promise<void>;

export function GetUserByEmail(arg1:string):Promise<models.User>;

export function GetUserById(arg1:string):Promise<models.User>;

export function GetUsers():Promise<Array<models.User>>;

export function LoginUser(arg1:models.User):Promise<string>;

export function Migration():Promise<void>;

export function RefreshToken(arg1:string):Promise<string>;

export function RegisterUser(arg1:models.User):Promise<void>;

export function TimerMultiple():Promise<void>;

export function TimerOff():Promise<void>;

export function UpdateUser(arg1:models.User):Promise<void>;
